-- VB MCM_CLEAN_PAC.SP_UM / SP_UK の全件孤児削除をSQL Serverへ移植。
-- 通常の画面保存からは呼ばない。全アプリ停止・バックアップ取得後の保守作業専用。
CREATE OR ALTER PROCEDURE MCM.MCM_WEB_CLEAN_UM_ALL
AS
BEGIN
 SET NOCOUNT ON;
 SET XACT_ABORT ON;
 BEGIN TRANSACTION;
 BEGIN TRY
 DELETE FROM MCM.MCM_UM_KIHON_MITSUMORI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_BRAND P WHERE P.UM_KIHON_MITSUMORI_ID=MCM_UM_KIHON_MITSUMORI.UM_KIHON_MITSUMORI_ID);
 DELETE FROM MCM.MCM_UM_KIHON_BRAND WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_MITSUMORI P WHERE P.UM_KIHON_MITSUMORI_ID=MCM_UM_KIHON_BRAND.UM_KIHON_MITSUMORI_ID);
 DELETE FROM MCM.MCM_UM_KIKIKOSEI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_BRAND P WHERE P.UM_KIHON_BRAND_ID=MCM_UM_KIKIKOSEI.UM_KIHON_BRAND_ID);
 DELETE FROM MCM.MCM_UM_KIKIMEISAI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIKIKOSEI P WHERE P.UM_KIKIKOSEI_ID=MCM_UM_KIKIMEISAI.UM_KIKIKOSEI_ID);
 DELETE FROM MCM.MCM_UM_KOTAIMEISAI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIKIMEISAI P WHERE P.UM_KIKIMEISAI_ID=MCM_UM_KOTAIMEISAI.UM_KIKIMEISAI_ID);
 DELETE FROM MCM.MCM_UM_TANKA WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIKIMEISAI P WHERE P.UM_KIKIMEISAI_ID=MCM_UM_TANKA.UM_KIKIMEISAI_ID);
 DELETE FROM MCM.MCM_UM_MITSUMORI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_MITSUMORI P WHERE P.UM_KIHON_MITSUMORI_ID=MCM_UM_MITSUMORI.UM_KIHON_MITSUMORI_ID);
 DELETE FROM MCM.MCM_UM_BRAND WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_BRAND P WHERE P.UM_KIHON_BRAND_ID=MCM_UM_BRAND.UM_KIHON_BRAND_ID);
 DELETE FROM MCM.MCM_UM_TENPU WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_MITSUMORI P WHERE P.UM_KIHON_MITSUMORI_ID=MCM_UM_TENPU.UM_KIHON_MITSUMORI_ID);
 COMMIT;
 END TRY
 BEGIN CATCH
 IF XACT_STATE()<>0 ROLLBACK;
 THROW;
 END CATCH
END;
GO
CREATE OR ALTER PROCEDURE MCM.MCM_WEB_CLEAN_UK_ALL
AS
BEGIN
 SET NOCOUNT ON;
 SET XACT_ABORT ON;
 BEGIN TRANSACTION;
 BEGIN TRY
 DELETE FROM MCM.MCM_UK_KEIYAKU WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKAN P WHERE P.UK_KEIYAKU_ID=MCM_UK_KEIYAKU.UK_KEIYAKU_ID);
 DELETE FROM MCM.MCM_UK_KIKAN WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KEIYAKU P WHERE P.UK_KEIYAKU_ID=MCM_UK_KIKAN.UK_KEIYAKU_ID);
 DELETE FROM MCM.MCM_UK_BRAND WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKAN P WHERE P.UK_KIKAN_ID=MCM_UK_BRAND.UK_KIKAN_ID);
 DELETE FROM MCM.MCM_UK_KIKIKOSEI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_BRAND P WHERE P.UK_BRAND_ID=MCM_UK_KIKIKOSEI.UK_BRAND_ID);
 DELETE FROM MCM.MCM_UK_KIKIMEISAI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKIKOSEI P WHERE P.UK_KIKIKOSEI_ID=MCM_UK_KIKIMEISAI.UK_KIKIKOSEI_ID);
 DELETE FROM MCM.MCM_UK_KOTAIMEISAI WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKIMEISAI P WHERE P.UK_KIKIMEISAI_ID=MCM_UK_KOTAIMEISAI.UK_KIKIMEISAI_ID);
 DELETE FROM MCM.MCM_UK_MITSUMORI_BRAND WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_BRAND P WHERE P.UK_BRAND_ID=MCM_UK_MITSUMORI_BRAND.UK_BRAND_ID);
 DELETE FROM MCM.MCM_UK_TENKEN WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKAN P WHERE P.UK_KIKAN_ID=MCM_UK_TENKEN.UK_KIKAN_ID);
 DELETE FROM MCM.MCM_UK_SEIBAN WHERE NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KEIYAKU P WHERE P.UK_KEIYAKU_ID=MCM_UK_SEIBAN.UK_KEIYAKU_ID);
 COMMIT;
 END TRY
 BEGIN CATCH
 IF XACT_STATE()<>0 ROLLBACK;
 THROW;
 END CATCH
END;
GO
