-- SQL Server用。アプリケーションを停止してDB管理者が一度実行する。GO区切りに対応したツールを使用。
-- 既存のVB/Oracle手続きや既存テーブル定義を変更しない。
IF OBJECT_ID('MCM.MCM_WEB_MAIL_OUTBOX','U') IS NULL
BEGIN
 CREATE TABLE MCM.MCM_WEB_MAIL_OUTBOX (
  MAIL_ID varchar(36) NOT NULL PRIMARY KEY,
  UM_KIHON_MITSUMORI_ID numeric(18,0) NOT NULL,
  REQUESTED_BY nvarchar(50) NOT NULL,
  FROM_ADDRESS nvarchar(254) NOT NULL,
  TO_ADDRESS nvarchar(254) NOT NULL,
  SUBJECT nvarchar(200) NOT NULL,
  BODY nvarchar(max) NOT NULL,
  STATUS varchar(12) NOT NULL CHECK (STATUS IN ('PENDING','SENDING','SENT','FAILED','SKIPPED')),
  ATTEMPTS int NOT NULL DEFAULT 0,
  LAST_ERROR nvarchar(200) NULL,
  CREATED_DT datetime2(7) NOT NULL,
  UPDATED_DT datetime2(7) NOT NULL
 );
 CREATE INDEX IX_MCM_WEB_MAIL_ESTIMATE ON MCM.MCM_WEB_MAIL_OUTBOX(UM_KIHON_MITSUMORI_ID,REQUESTED_BY,CREATED_DT);
END;
GO
CREATE OR ALTER PROCEDURE MCM.MCM_WEB_SP_UM @ID numeric(18,0)
AS
BEGIN
 SET NOCOUNT ON;
 SET XACT_ABORT ON;
 IF @ID IS NULL OR NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_KIHON_BRAND WHERE UM_KIHON_MITSUMORI_ID=@ID) OR NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_MITSUMORI WHERE UM_KIHON_MITSUMORI_ID=@ID)
  THROW 51001,N'保存対象の親子情報が不足しています。',1;
 DELETE FROM MCM.MCM_UM_TANKA WHERE UM_KIKIMEISAI_ID IN (SELECT M.UM_KIKIMEISAI_ID FROM MCM.MCM_UM_KIKIMEISAI M JOIN MCM.MCM_UM_KIKIKOSEI K ON K.UM_KIKIKOSEI_ID=M.UM_KIKIKOSEI_ID JOIN MCM.MCM_UM_KIHON_BRAND B ON B.UM_KIHON_BRAND_ID=K.UM_KIHON_BRAND_ID WHERE B.UM_KIHON_MITSUMORI_ID=@ID) AND NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_MITSUMORI P WHERE P.UM_MITSUMORI_ID=MCM_UM_TANKA.UM_MITSUMORI_ID AND P.UM_KIHON_MITSUMORI_ID=@ID);
 DELETE FROM MCM.MCM_UM_BRAND WHERE UM_KIHON_BRAND_ID IN (SELECT UM_KIHON_BRAND_ID FROM MCM.MCM_UM_KIHON_BRAND WHERE UM_KIHON_MITSUMORI_ID=@ID) AND NOT EXISTS (SELECT 1 FROM MCM.MCM_UM_MITSUMORI P WHERE P.UM_MITSUMORI_ID=MCM_UM_BRAND.UM_MITSUMORI_ID AND P.UM_KIHON_MITSUMORI_ID=@ID);
END;
GO
CREATE OR ALTER PROCEDURE MCM.MCM_WEB_SP_UK @ID numeric(18,0)
AS
BEGIN
 SET NOCOUNT ON;
 IF @ID IS NULL OR NOT EXISTS (SELECT 1 FROM MCM.MCM_UK_KIKAN WHERE UK_KEIYAKU_ID=@ID)
  THROW 51002,N'保存対象の契約期間が不足しています。',1;
 -- 機器の変更はアプリ側で個体→明細→構成→ブランドの順に削除済み。
END;
GO
