-- 対象の見積契約時間IDを設定。NULLのままならデータ行は返しません。
DECLARE @Id decimal(18,0) = NULL;
SELECT V.TM_KEIYAKUJIKAN_ID, V.TK_KEIYAKU_ID,
       T.JOTAI AS 契約状態コード, M.JOTAI AS 見積契約時間状態コード,
       V.JOTAI AS ビュー表示状態, V.MITSUMORI_DEL, V.KEIYAKU_KEIYAKU, V.KEIYAKU_DEL
FROM MCM.MCM_1003_V V
LEFT JOIN MCM.MCM_TM_KEIYAKUJIKAN M ON M.TM_KEIYAKUJIKAN_ID=V.TM_KEIYAKUJIKAN_ID
LEFT JOIN MCM.MCM_TK_KEIYAKU T ON T.TK_KEIYAKU_ID=V.TK_KEIYAKU_ID
WHERE V.TM_KEIYAKUJIKAN_ID=@Id;

-- 実環境のビュー定義（閲覧権限がないとNULLになる場合があります）。
SELECT OBJECT_DEFINITION(OBJECT_ID(N'MCM.MCM_1003_V')) AS 一覧ビュー定義,
       OBJECT_DEFINITION(OBJECT_ID(N'MCM.MCM_TM_KEIYAKU_NO_V')) AS 契約結合ビュー定義;
